export default {
    OTP_SENT: 'OTP SENT SUCCESSFULLY TO YOUR EMAIL',
    EMAIL_FOUND: 'This email is already in use try diffrent or login',
    INVALID_OTP: 'OTP IS NOT VALID',
    SIGNUP_SUCCESS: 'Your account created successfully',
    USER_NOT_FOUND:
        'sorry! we are not able to find user by this email please check email or try to register',
    NOT_MATCHED:
        'oops! think you entered wrong password! check your email or password',
    USER_LOGGEDIN: 'You have logged in successfully',
    LOGGED_OUT: 'Logged out successfully',
    USER_FOUND: 'user detail found in db',
    JOB_ADDED: 'New Job Added Successfully',
    JOB_UPDATED: 'Your job has been updated successfully',
    JOB_DELETED: 'Your posted job has been deleted successfully',
    BID_APPLIED: 'You have successfully applied for this bid',
    BID_NOT_FOUND: "Sorry we are not able to find the bid you are looking for.",
    UNAUTH_USER: "Sorry! But you are not autherized for this action.",
    PORJECT_ADDED: "Project successfully added to your portfolio",
    PROJECT_NOT_FOUND: "Sorry! we could not find the project you are looking for",
    PROJECT_UPDATED: "Your project detail has been updated successfully",
    PROJECT_REMOVED: "Project removed.",
    DATA_FOUND: 'Data Fetched Successfully',
    DATA_ADDED: "Data added successfully",
    DATA_NOT_FOUND: "The data you are trying to fetch don't exist",
};
